[build]
  base = "frontend"
  publish = "build"
  command = "npm run build"
 
[build.environment]
  NODE_VERSION = "18"
  NODE_OPTIONS = "--max-old-space-size=4096"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
