import {
  Train,
  Plane,
  MapPin,
  Coins,
  Trees,
  Landmark,
  Utensils,
  Martini,
  Amphora,
  Coffee,
  ShoppingBag,
  Star,
  PartyPopper,
  Bot,
  Gamepad,
  Octagon,
  FerrisWheel,
  Shield,
  Castle,
  Cross,
  Church,
  Grape,
  Hotel,
  Building,
  WavesLadder,
  Home,
  Accessibility,
  Bed,
  Wifi,
  Breakfast,
  ParkingCircle,
  Bus,
  Swimmer,
  Dumbbell,
  Wheelchair,
  Dog,
  Baby,
  Heart,
  Briefcase,
  Mountain,
  Soup,
  Fish,
  Leaf,
  ShoppingCart,
  FastForward,
  EggFried,
  ChefHat,
} from "lucide-react";
import BedroomChildOutlinedIcon from "@mui/icons-material/BedroomChildOutlined";
import SpaOutlinedIcon from "@mui/icons-material/SpaOutlined";
import HotTubOutlinedIcon from "@mui/icons-material/HotTubOutlined";
import TempleBuddhistOutlinedIcon from "@mui/icons-material/TempleBuddhistOutlined";
import BeachAccessOutlinedIcon from "@mui/icons-material/BeachAccessOutlined";

export const generalTags = {
  budget: [
    { icon: <Coins />, title: "Gratis" },
    { icon: <Coins />, title: "Económico" },
    { icon: <Coins />, title: "Moderado" },
    { icon: <Coins />, title: "Lujo" },
  ],
  location: [
    { icon: <Train />, title: "Cerca de estaciones de tren o metro" },
    { icon: <Plane />, title: "Cerca de aeropuertos" },
    { icon: <MapPin />, title: "Cerca de áreas de puntos de interés" },
  ],
  season: [
    { icon: <Train />, title: "Otoño" },
    { icon: <Plane />, title: "Verano" },
    { icon: <Plane />, title: "Primavera" },
    { icon: <MapPin />, title: "Invierno" },
  ],
};

export const attractionTags = [
  { icon: <Trees size={16} />, title: "Naturaleza" },
  { icon: <BeachAccessOutlinedIcon size={16} />, title: "Playa" },
  { icon: <Landmark size={16} />, title: "Monumento" },
  { icon: <Utensils size={16} />, title: "Gastronomía" },
  { icon: <Martini size={16} />, title: "Noche" },
  { icon: <Amphora size={16} />, title: "Museo" },
  { icon: <Coffee size={16} />, title: "Cafés" },
  { icon: <ShoppingBag size={16} />, title: "Shopping" },
  { icon: <Star size={16} />, title: "Ocio" },
  { icon: <PartyPopper size={16} />, title: "Festival" },
  { icon: <Bot size={16} />, title: "Tecnología" },
  { icon: <Gamepad size={16} />, title: "Juegos" },
  { icon: <Octagon size={16} />, title: "Anime" },
  { icon: <FerrisWheel size={16} />, title: "Parques temáticos" },
  { icon: <Shield size={16} />, title: "Samurai" },
  { icon: <Church size={16} />, title: "Templo Budista" },
  { icon: <Castle size={16} />, title: "Castillos" },
  { icon: <Cross size={16} />, title: "Templo Cristiano" },
  { icon: <TempleBuddhistOutlinedIcon size={16} />, title: "Templo Sintoísta" },
  { icon: <Church size={16} />, title: "Templo Hindú" },
  { icon: <HotTubOutlinedIcon size={16} />, title: "Aguas Termales" },
  { icon: <Grape size={16} />, title: "Viñedos" },
];

export const hotelTags = {
  accommodations: [
    { icon: <Hotel />, title: "Hoteles de lujo" },
    { icon: <SpaOutlinedIcon />, title: "Ryokan (tradicional)" },
    { icon: <BedroomChildOutlinedIcon />, title: "Hoteles cápsula" },
    { icon: <Building />, title: "Hoteles de negocios" },
    { icon: <Home />, title: "Apartamentos" },
    { icon: <Bed />, title: "Hostales" },
  ],
  hotelServices: [
    { icon: <Wifi />, title: "Wi-Fi gratis" },
    { icon: <EggFried />, title: "Desayuno incluido" },
    { icon: <ParkingCircle />, title: "Aparcamiento gratuito" },
    { icon: <Bus />, title: "Transporte al aeropuerto" },
    { icon: <WavesLadder />, title: "Piscina" },
    { icon: <Dumbbell />, title: "Gimnasio" },
    { icon: <Utensils />, title: "Restaurante en el hotel" },
    { icon: <Accessibility />, title: "Accesible" },
    { icon: <Dog />, title: "Admite mascotas" },
  ],
  typeTrip: [
    { icon: <Baby />, title: "Familiar" },
    { icon: <Heart />, title: "Luna de miel" },
    { icon: <Briefcase />, title: "De negocios" },
    { icon: <ShoppingCart />, title: "Amigable para mochileros" },
    { icon: <Mountain />, title: "Para aventureros" },
  ],
};

export const restaurantTags = {
  restaurantTypes: [
    { icon: <Soup />, title: "Restaurantes tradicionales" },
    { icon: <FastForward />, title: "Cadenas de comida rápida" },
    { icon: <Coffee />, title: "Cafeterías y cafés" },
    { icon: <ChefHat />, title: "Restaurantes de alta cocina" },
    { icon: <ShoppingBag />, title: "Food trucks" },
    { icon: <Soup />, title: "Ramen" },
    { icon: <Soup />, title: "Sushi" },
  ],
  cuisines: [
    { icon: <Soup />, title: "Cocina japonesa tradicional" },
    { icon: <Soup />, title: "Internacional" },
    { icon: <Soup />, title: "Fusión" },
    { icon: <Soup />, title: "Cocina vegetariana/vegana" },
    { icon: <Soup />, title: "Cocina sin gluten" },
    { icon: <Soup />, title: "Cocina halal" },
    { icon: <Soup />, title: "Cocina kosher" },
    { icon: <Soup />, title: "Rápida" },
    { icon: <Soup />, title: "Cocina de autor" },
    { icon: <Soup />, title: "Con espectáculo" },
    { icon: <Soup />, title: "Familiar" },
    { icon: <Soup />, title: "Romántica" },
    { icon: <Soup />, title: "Negocios" },
    { icon: <Soup />, title: "Ocasiones especiales" },
  ],
  restaurantServices: [
    { icon: <Wifi />, title: "Wi-Fi gratis" },
    { icon: <Utensils />, title: "Menú en inglés" },
    { icon: <Utensils />, title: "Reservas en línea" },
    { icon: <Utensils />, title: "Entregas a domicilio" },
    { icon: <Utensils />, title: "Terraza o comedor al aire libre" },
    { icon: <Utensils />, title: "Opciones de comida para llevar" },
    { icon: <Dog />, title: "Admite mascotas" },
    { icon: <Leaf />, title: "Ingredientes orgánicos" },
    { icon: <Fish />, title: "Mariscos frescos" },
    { icon: <Baby />, title: "Menús infantiles" },
  ],
};
